# Generated by Django 4.2 on 2023-08-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_id', models.IntegerField()),
                ('time_stamp', models.CharField(max_length=200)),
                ('descriptions', models.CharField(max_length=300)),
                ('modified_descriptions', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
