# Generated by Django 4.2 on 2023-09-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='username',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='description',
            name='modified_descriptions',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
