# Generated by Django 4.2 on 2023-10-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0002_description_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='ai_or_human',
            field=models.CharField(default='ai', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='group_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='group_star',
            field=models.IntegerField(default=0),
        ),
    ]
