# Generated by Django 4.2 on 2023-11-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0003_description_ai_or_human_description_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='description',
            name='time_stamp_end',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='time_stamp_start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
