# Generated by Django 4.2 on 2023-08-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_path',
        ),
    ]
