# Generated by Django 4.2 on 2023-09-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='username',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
