# Generated by Django 4.2 on 2023-10-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='public_or_private',
            field=models.CharField(default='public', max_length=200),
            preserve_default=False,
        ),
    ]
